version: '3.8'

services:
  alto-api:
    build: .
    image: alto-api:latest
    container_name: alto-api
    hostname: alto-api
    depends_on:
      alto-mysql:
        condition: service_healthy
    networks:
      - alto-network
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/usr/src/app/storage
    environment:
      - DATABASE_HOST=alto-mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=alto
      - DATABASE_USER=root_user
      - DATABASE_PASSWORD=Yf7@qP9!xLm2wM3z

  alto-mysql:
    image: mysql:8.0
    container_name: alto-mysql
    hostname: alto-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Yf7@qP9!xLm2wM3z
      MYSQL_DATABASE: alto
      MYSQL_USER: root_user
      MYSQL_PASSWORD: Yf7@qP9!xLm2wM3z
    networks:
      - alto-network
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
    volumes:
      - alto-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pYf7@qP9!xLm2wM3z"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  alto-network:
    driver: bridge

volumes:
  alto-db-data:
